name: Validate Policy Bot Config
description: Validates the Policy Bot configuration file.

inputs:
  policy:
    description: |
      Path to the Policy Bot configuration file.
    default: .policy.yml

  validation_endpoint:
    description: |
      Validation API endpoint.
    required: true

runs:
  using: composite
  steps:
    - name: Validate Policy Bot config
      shell: bash
      env:
        POLICY: ${{ inputs.policy }}
        VALIDATION_ENDPOINT: ${{ inputs.validation_endpoint }}
      run: |
        curl \
          --silent \
          --show-error \
          --fail-with-body \
          --request PUT \
          --upload-file "${POLICY}" \
          --url "${VALIDATION_ENDPOINT}"
